version: "3"

services:
  ruby:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - bundle-volume:/usr/local/bundle
    command: sleep infinity
volumes:
  bundle-volume: null